import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { cookies } from "next/headers";
import { verify } from "jsonwebtoken";

// Helper: Check if user is Admin
async function isAdmin() {
  const cookieStore = await cookies();
  const token = cookieStore.get("session")?.value || cookieStore.get("auth_token")?.value;
  if (!token) return false;
  try {
    const decoded: any = verify(token, process.env.JWT_SECRET || "secret");
    // In a real app, strictly check decoded.role === 'ADMIN'
    // For now, we assume if they have a valid token they can access (Upgrade this later!)
    return true; 
  } catch { return false; }
}

export async function GET() {
  if (!await isAdmin()) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  
  const pages = await prisma.dynamicPage.findMany({ 
    orderBy: { updatedAt: 'desc' },
    select: { id: true, title: true, slug: true, isPublished: true, updatedAt: true }
  });
  return NextResponse.json(pages);
}

export async function POST(req: Request) {
  if (!await isAdmin()) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  
  const body = await req.json();
  
  try {
    const page = await prisma.dynamicPage.create({
      data: {
        title: body.title,
        slug: body.slug,
        isPublished: true,
        // Default Content: A simple Hero section
        sections: {
          create: {
            type: "HERO",
            order: 0,
            content: {
              heading: body.title,
              subheading: "This page was generated by the AfyaDiet CMS.",
              ctaText: "Return Home",
              ctaLink: "/"
            }
          }
        }
      }
    });
    return NextResponse.json(page);
  } catch (e) {
    console.error(e);
    return NextResponse.json({ error: "Slug already exists or database error" }, { status: 400 });
  }
}

export async function DELETE(req: Request) {
  if (!await isAdmin()) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  
  const { searchParams } = new URL(req.url);
  const id = searchParams.get("id");
  
  if (!id) return NextResponse.json({ error: "ID required" }, { status: 400 });

  await prisma.dynamicPage.delete({ where: { id } });
  return NextResponse.json({ success: true });
}